In [15]:
import numpy as np

a=np.array([[1,29,34,56,35],[48,50,34,66,44],[24,56,8,43,23],[34,67,32,64,62],[57,98,66,35,74]])
print("A=",a)
b=int(input("Enter the row: "))
c=int(input("Enter the column: "))
print("Element= ",a[b,c])

N4=[]
if b+1<5:
    N4.append(a[b+1,c])
if c+1<5:
    N4.append(a[b,c+1])
if b-1>=0:
    N4.append(a[b-1,c])
if c-1>=0:
    N4.append(a[b,c-1])

print("N4= ",N4)

Nd=[]
if b+1<5 and c+1<5:
    Nd.append(a[b+1,c+1])
if c+1<5 and b-1>=0:
    Nd.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    Nd.append(a[b-1,c-1])
if c-1>=0 and b+1<5:
    Nd.append(a[b+1,c-1])

print("Nd= ",Nd)



N8=[]
if b+1<5:
    N8.append(a[b+1,c])
if c+1<5:
    N8.append(a[b,c+1])
if b-1>=0:
    N8.append(a[b-1,c])
if c-1>=0:
    N8.append(a[b,c-1])
if b+1<5 and c+1<5:
    N8.append(a[b+1,c+1])
if c+1<5 and b-1>=0:
    N8.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    N8.append(a[b-1,c-1])
if c-1>=0 and b+1<5:
    N8.append(a[b+1,c-1])

print("N8= ",N8)




A= [[ 1 29 34 56 35]
 [48 50 34 66 44]
 [24 56  8 43 23]
 [34 67 32 64 62]
 [57 98 66 35 74]]
Element=  1
N4=  [np.int64(48), np.int64(29)]
Nd=  [np.int64(50)]
N8=  [np.int64(48), np.int64(29), np.int64(50)]


In [16]:
N8=N4+Nd
print(N8)

[np.int64(48), np.int64(29), np.int64(50)]


In [17]:
N4=[]
if b+1<5:
    N4.append((b+1,c))
if c+1<5:
    N4.append((b,c+1))
if b-1>=0:
    N4.append((b-1,c))
if c-1>=0:
    N4.append((b,c-1))

print("N4= ",N4)

N4=  [(1, 0), (0, 1)]


In [20]:
avg = sum(N8)/len(N8)
print(avg)

if 1 <= b <= 3 and 1 <= c <= 3:
    center=a[b,c]
    grid=N8.copy()
    grid.insert(4,center)
    q=np.reshape(grid,(3,3))
    print(q)
else:
    print("Neighbourhood cannot be extracted (border pixel)")


42.333333333333336
Neighbourhood cannot be extracted (border pixel)
